name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Install dependencies
      - name: Install dependencies
        run: npm install


      # Run tests with coverage
      - name: Run tests and generate coverage
        run: npm run test:coverage

      # Display lcov.info content for debugging
      - name: Display lcov.info content
        run: cat ./coverage/lcov.info

      # Upload coverage to Codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ github.workspace }}/coverage/lcov.info  # Ensure this path is correct
          name: node-coverage-report
          fail_ci_if_error: true 
          verbose: true

  
        
  
